<?php
require_once('tcpdf/tcpdf.php'); // Include the TCPDF library

// Database connection
$servername = "localhost";
$username = "root"; // Your MySQL username
$password = ""; // Your MySQL password
$dbname = "pos"; // Database name

$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Get log_id from the URL
$log_id = isset($_GET['log_id']) ? intval($_GET['log_id']) : 0;

// Fetch customer log details
$log_query = "SELECT * FROM testcustomer_logs WHERE log_id = ?";
$stmt_log = $conn->prepare($log_query);
$stmt_log->bind_param("i", $log_id);
$stmt_log->execute();
$log_result = $stmt_log->get_result();
$customer_log = $log_result->fetch_assoc();

// Fetch associated products with prices directly from testcustomer_products
$product_query = "SELECT cp.product_needed, cp.quantity, cp.price 
                  FROM testcustomer_products cp 
                  WHERE cp.log_id = ?";
$stmt_product = $conn->prepare($product_query);
$stmt_product->bind_param("i", $log_id);
$stmt_product->execute();
$product_result = $stmt_product->get_result();
$products_with_prices = $product_result->fetch_all(MYSQLI_ASSOC);

// Fetch associated services with prices from the services table
$service_query = "SELECT cs.service_needed, s.price 
                  FROM testcustomer_services cs 
                  JOIN services s ON cs.service_needed = s.service_name 
                  WHERE cs.log_id = ?";
$stmt_service = $conn->prepare($service_query);
$stmt_service->bind_param("i", $log_id);
$stmt_service->execute();
$service_result = $stmt_service->get_result();
$services = $service_result->fetch_all(MYSQLI_ASSOC);

// Close the statements and connection
$stmt_log->close();
$stmt_product->close();
$stmt_service->close();
$conn->close();

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Company');
$pdf->SetTitle('Quotation');
$pdf->SetSubject('Quotation Details');
$pdf->SetKeywords('TCPDF, PDF, quotation, test');

// Set default header data
$pdf->SetHeaderData('', 0, 'Quotation', 'Generated by Your Company');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add customer details
$html = '<h1>Quotation</h1>';
$html .= '<h2>Customer Details</h2>';
$html .= '<p><strong>Name:</strong> ' . htmlspecialchars($customer_log['name']) . '</p>';
$html .= '<p><strong>Customer ID:</strong> ' . htmlspecialchars($customer_log['icnumber']) . '</p>';
$html .= '<p><strong>Contact Info:</strong> ' . htmlspecialchars($customer_log['contact_info']) . '</p>';
$html .= '<p><strong>Problem Description:</strong> ' . nl2br(htmlspecialchars($customer_log['problem_desc'])) . '</p>';
$html .= '<p><strong>Follow-up Date:</strong> ' . htmlspecialchars($customer_log['followupdate']) . '</p>';

// Add products needed with prices
$html .= '<h2>Products Needed</h2>';
$html .= '<table border="1" cellpadding="4"><thead><tr><th>Product</th><th>Quantity</th><th>Price</th></tr></thead><tbody>';
if (!empty($products_with_prices)) {
    foreach ($products_with_prices as $product) {
        $html .= '<tr>';
        $html .= '<td>' . htmlspecialchars($product['product_needed']) . '</td>'; // Original product name
        $html .= '<td>' . htmlspecialchars($product['quantity']) . '</td>';
        $html .= '<td>' . htmlspecialchars($product['price']) . '</td>';
        $html .= '</tr>';
    }
} else {
    $html .= '<tr><td colspan="3">No products needed.</td></tr>';
}
$html .= '</tbody></table>';

// Add services needed with prices
$html .= '<h2>Services Needed</h2>';
$html .= '<table border="1" cellpadding="4"><thead><tr><th>Service</th><th>Price</th></tr></thead><tbody>';
if (!empty($services)) {
    foreach ($services as $service) {
        $html .= '<tr><td>' . htmlspecialchars($service['service_needed']) . '</td>';
        $html .= '<td>' . htmlspecialchars($service['price']) . '</td></tr>';
    }
} else {
    $html .= '<tr><td colspan="2">No services needed.</td></tr>';
}
$html .= '</tbody></table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('quotation.pdf', 'D'); // 'D' for download
?>
